= Quarkus Nagios

include::./includes/attributes.adoc[]

This extension provides health checks in the Nagios format, simplifying the integration of Quarkus applications with Nagios.

== Installation

If you want to use this extension, you need to add the `io.quarkiverse.nagios:quarkus-nagios` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.nagios</groupId>
    <artifactId>quarkus-nagios</artifactId>
    <version>{project-version}</version>
</dependency>
----

== Usage

=== Nagios Setup

Use this shell script to set up an active service check in nagios:

----
#!/bin/bash

url=$1

if [ -z "$url" ]; then
    echo "usage: $0 URL"
    exit
fi

declare -A statusmap=(
  ["OK"]="0"
  ["WARN"]="1"
  ["WARNING"]="1"
  ["CRIT"]="2"
  ["CRITICAL"]="2"
  ["UNKNOWN"]="3"
)

result=$(curl --fail --max-time 15 --connect-timeout 7 $url 2>/dev/null)

status=${result%%:*}

exitcode=3
if [ -z "$result" ]; then
    result="UNKNOWN: Got no result from $url"
elif [ -z "${statusmap[$status]}" ]; then
    exitcode=${statusmap[$status]}
fi

echo "$result"
exit $exitcode
----

=== Nagios Health Checks

The Quarkus Nagios extensions works with all health checks. However, this extension provides an implementation of the Health Check API that allows to use additional nagios-specific features, such as performance graphs and additional status values.

----
@Wellness
@Singleton
public class QueueSizeHealth implements HealthCheck {

    @Override
    public NagiosCheckResponse call() {
        int queueSize = ...
        return QUEUE_SIZE.result(queueSize).asResponse();
    }

    private static final NagiosCheck QUEUE_SIZE = NagiosCheck.named("queue size")
            .performance()           // export as performance data
            .warningIf().above(30)   // warning range
            .criticalIf().above(100) // critical range
            .build();
}
----


[[extension-configuration-reference]]
== Extension Configuration Reference


include::includes/quarkus-nagios.adoc[leveloffset=+1, opts=optional]
